# <center><img src="https://github.com/insaid2018/Term-1/blob/master/Images/INSAID_Full%20Logo.png?raw=true" width="240" height="100" /></center>


## **<center>ML1: TELECOM CHURN PREDICTION</center>**

<a name = Section2></a>
# **Problem Statement**
---

The company suffers from the following problems:

- Due to the boom in the telecom industry with 4G technology, it has become a pain in the neck for the company to retain their customers.

- They are in the middle of setting up more cell sites on the 4G network to improve their 4G services.
It is plausible for customers to choose 4G services over 3G services due to benefits of cost, speed, latency etc.

- In return, they have decided to find a more optimal way and hired a team of data scientists to solve this problem.

<a name = Section33></a>
### **Importing Libraries**

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

import warnings
warnings.filterwarnings("ignore")  

<a name = Section33></a>
### **Data Acquisition**

In [143]:
train=pd.read_csv('Churn_train.csv')
train.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  5442-PPTJY    Male              0     Yes        Yes      12          Yes   
1  6261-RCVNS  Female              0      No         No      42          Yes   
2  2176-OSJUV    Male              0     Yes         No      71          Yes   
3  6161-ERDGD    Male              0     Yes        Yes      71          Yes   
4  2364-UFROM    Male              0      No         No      30          Yes   

  MultipleLines InternetService       OnlineSecurity  ...  \
0            No              No  No internet service  ...   
1            No             DSL                  Yes  ...   
2           Yes             DSL                  Yes  ...   
3           Yes             DSL                  Yes  ...   
4            No             DSL                  Yes  ...   

      DeviceProtection          TechSupport          StreamingTV  \
0  No internet service  No internet service  No internet service   
1                  Yes                  Yes                   No   
2                   No                  Yes                   No   
3                  Yes                  Yes                  Yes   
4                   No                  Yes                  Yes   

       StreamingMovies  Contract PaperlessBilling              PaymentMethod  \
0  No internet service  Two year               No               Mailed check   
1                  Yes  One year               No    Credit card (automatic)   
2                   No  Two year               No  Bank transfer (automatic)   
3                  Yes  One year               No           Electronic check   
4                   No  One year               No           Electronic check   

  MonthlyCharges  TotalCharges Churn  
0          19.70        258.35    No  
1          73.90       3160.55   Yes  
2          65.15       4681.75    No  
3          85.45       6300.85    No  
4          70.40       2044.75    No  

[5 rows x 21 columns]

### Dataset Feature Description
The Dataset contains the following columns:

||Column Name|Description|
|:--|:--|:--|
||**CustomerID**| Passenger Identity |
||**Gender	Whether**| Whether the customer is a male or a female |
||**SeniorCitizen**| Whether the customer is a senior citizen or not (1, 0) |
||**Partner	Whether**| the customer has a partner or not (Yes, No) |
||**Dependents**| Whether the customer has dependents or not (Yes, No)|
||**Tenure**| Number of months the customer has stayed with the company |
||**PhoneService**| Whether the customer has a phone service or not (Yes, No) |
||**MultipleLines**| Whether the customer has multiple lines or not (Yes, No, No phone service) |
||**InternetService**| Customer’s internet service provider (DSL, Fiber optic, No)|
||**OnlineSecurity**| Whether the customer has online security or not (Yes, No, No internet service)|
||**OnlineBackup**| Whether the customer has online backup or not (Yes, No, No internet service)|
||**DeviceProtection**| Whether the customer has device protection or not (Yes, No, No internet service)|
||**TechSupport**| Whether the customer has tech support or not (Yes, No, No internet service) |
||**StreamingTV**| Whether the customer has streaming TV or not (Yes, No, No internet service)|
||**StreamingMovies**| Whether the customer has streaming movies or not (Yes, No, No internet service) |
||**Contract**| The contract term of the customer (Month-to-month, One year, Two year)|
||**PaperlessBilling**| Whether the customer has paperless billing or not (Yes, No)|
||**PaymentMethod**| The customer’s payment method (Electronic check, Mailed check, Bank transfer (automatic), Credit card (automatic))|
||**MonthlyCharges**| The amount charged to the customer monthly|
||**TotalCharges**| The total amount charged to the customer|
||**Churn**| Whether the customer churned or not (Yes or No)|

<a name = Section41></a>
### **Data Info, Data Description and Null Value Checking**

- In this section we will get **description** and **statistics** about the data.

In [25]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        5634 non-null   object 
 1   gender            5634 non-null   object 
 2   SeniorCitizen     5634 non-null   int64  
 3   Partner           5634 non-null   object 
 4   Dependents        5634 non-null   object 
 5   tenure            5634 non-null   int64  
 6   PhoneService      5634 non-null   object 
 7   MultipleLines     5634 non-null   object 
 8   InternetService   5634 non-null   object 
 9   OnlineSecurity    5634 non-null   object 
 10  OnlineBackup      5634 non-null   object 
 11  DeviceProtection  5634 non-null   object 
 12  TechSupport       5634 non-null   object 
 13  StreamingTV       5634 non-null   object 
 14  StreamingMovies   5634 non-null   object 
 15  Contract          5634 non-null   object 
 16  PaperlessBilling  5634 non-null   object 


In [26]:
train.describe().T

count       mean        std    min   25%     50%    75%  \
SeniorCitizen   5634.0   0.161874   0.368368   0.00   0.0   0.000   0.00   
tenure          5634.0  32.277955  24.555211   0.00   9.0  29.000  55.00   
MonthlyCharges  5634.0  64.779127  30.104993  18.25  35.4  70.375  89.85   

                   max  
SeniorCitizen     1.00  
tenure           72.00  
MonthlyCharges  118.65

In [27]:
train['tenure'].value_counts()

1     485
72    283
2     194
3     165
71    147
     ... 
45     46
21     45
39     43
36     38
0       8
Name: tenure, Length: 73, dtype: int64

In [28]:
from pandas_profiling import ProfileReport
profile=ProfileReport(train,title='Pandas Profile Report')
profile.to_widgets()

Summarize dataset:   0%|          | 0/33 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [29]:
#Dropping customerID column as it is highly co-ordinality column
train.drop(columns=['customerID'],inplace=True)

In [30]:
train['PaymentMethod'].value_counts()

Electronic check             1893
Mailed check                 1305
Bank transfer (automatic)    1219
Credit card (automatic)      1217
Name: PaymentMethod, dtype: int64

In [31]:
#change the 'No phone/internet service' to 'No', because it's not adding any new informaion
train=train.replace(to_replace='No internet service',value='No')
train=train.replace(to_replace='No phone service',value='No')

In [32]:
train.sample(n=3)

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
1940    Male              0     Yes         No      18          Yes   
1439  Female              0      No         No      34          Yes   
4174    Male              0      No         No      31          Yes   

     MultipleLines InternetService OnlineSecurity OnlineBackup  \
1940           Yes             DSL             No          Yes   
1439           Yes     Fiber optic            Yes          Yes   
4174            No     Fiber optic             No          Yes   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
1940               No          No          No              No  Month-to-month   
1439              Yes          No         Yes             Yes  Month-to-month   
4174              Yes          No         Yes             Yes  Month-to-month   

     PaperlessBilling            PaymentMethod  MonthlyCharges TotalCharges  \
1940               No  Credit card (automatic)            56.8      1074.65   
1439              Yes             Mailed check           109.8      3587.25   
4174              Yes         Electronic check           101.4      3143.65   

     Churn  
1940    No  
1439   Yes  
4174    No

In [33]:
cols=['gender','Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup',
     'DeviceProtection','TechSupport','StreamingTV','StreamingMovies','Contract','PaperlessBilling','PaymentMethod','Churn']

In [34]:
le=LabelEncoder()

In [35]:
encodingdata=train[cols].apply(le.fit_transform)

In [36]:
train.drop(columns=cols,inplace=True)

In [37]:
train=train.join(encodingdata[cols])

In [38]:
train.sample(n=3)

SeniorCitizen  tenure  MonthlyCharges TotalCharges  gender  Partner  \
3748              0      11            29.6       346.45       0        1   
2981              1      28            25.7        734.6       0        1   
2905              0      62            24.4         1413       1        0   

      Dependents  PhoneService  MultipleLines  InternetService  \
3748           1             0              0                0   
2981           0             1              1                2   
2905           1             1              1                2   

      OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  \
3748               1             0                 0            0   
2981               0             0                 0            0   
2905               0             0                 0            0   

      StreamingTV  StreamingMovies  Contract  PaperlessBilling  PaymentMethod  \
3748            0                0         0                 1              2   
2981            0                0         0                 0              3   
2905            0                0         2                 1              3   

      Churn  
3748      0  
2981      0  
2905      0

In [39]:
train['TotalCharges'] = train['TotalCharges'].replace(' ', value=0)
train.TotalCharges = pd.to_numeric(train.TotalCharges)

In [40]:
ss=StandardScaler()

In [41]:
scalardata=ss.fit(train[['tenure','MonthlyCharges','TotalCharges']])
data=scalardata.transform(train[['tenure','MonthlyCharges','TotalCharges']])
data=pd.DataFrame(data,columns=['tenure','MonthlyCharges','TotalCharges'])
train.drop(columns=['tenure','MonthlyCharges','TotalCharges'],inplace=True)
train=train.join(data)

In [42]:
train.sample(n=3)

SeniorCitizen  gender  Partner  Dependents  PhoneService  MultipleLines  \
1717              0       0        0           0             1              0   
2783              0       1        1           0             1              1   
1458              0       0        1           1             1              1   

      InternetService  OnlineSecurity  OnlineBackup  DeviceProtection  \
1717                2               0             0                 0   
2783                0               0             0                 1   
1458                0               1             1                 0   

      TechSupport  StreamingTV  StreamingMovies  Contract  PaperlessBilling  \
1717            0            0                0         0                 0   
2783            0            0                0         0                 0   
1458            0            0                0         0                 1   

      PaymentMethod  Churn    tenure  MonthlyCharges  TotalCharges  
1717              3      0 -1.070253       -1.487564     -0.956762  
2783              1      0 -0.296418       -0.306592     -0.384838  
1458              1      0  0.110864       -0.177034     -0.062008

In [43]:
X=train.drop('Churn',axis=1)
y=train['Churn']

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

##### Working on Test dataset 

In [45]:
test=pd.read_csv('Churn_test.csv')

In [46]:
test.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  8879-ZKJOF  Female              0      No         No      41          Yes   
1  0201-MIBOL  Female              1      No         No      66          Yes   
2  1600-DILPE  Female              0      No         No      12          Yes   
3  8601-QACRS  Female              0      No         No       5          Yes   
4  7919-ZODZZ  Female              0     Yes        Yes      10          Yes   

  MultipleLines InternetService OnlineSecurity OnlineBackup DeviceProtection  \
0            No             DSL            Yes           No              Yes   
1           Yes     Fiber optic            Yes           No               No   
2            No             DSL             No           No               No   
3           Yes             DSL             No           No               No   
4            No             DSL             No          Yes              Yes   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0         Yes         Yes             Yes        One year              Yes   
1          No         Yes             Yes        Two year              Yes   
2          No          No              No  Month-to-month              Yes   
3          No          No              No  Month-to-month              Yes   
4          No          No             Yes        One year              Yes   

               PaymentMethod  MonthlyCharges TotalCharges  
0  Bank transfer (automatic)           79.85      3320.75  
1  Bank transfer (automatic)          102.40      6471.85  
2  Bank transfer (automatic)           45.00       524.35  
3               Mailed check           50.60       249.95  
4               Mailed check           65.90       660.05

In [47]:
test.drop(columns=['customerID'],inplace=True)

In [48]:
#change the 'No phone/internet service' to 'No', because it's not adding any new informaion
test=test.replace(to_replace='No internet service',value='No')
test=test.replace(to_replace='No phone service',value='No')

In [49]:
cols1=['gender','Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup',
     'DeviceProtection','TechSupport','StreamingTV','StreamingMovies','Contract','PaperlessBilling','PaymentMethod']

In [50]:
encodingdatatest=test[cols1].apply(le.fit_transform)

In [51]:
test.drop(columns=cols1,inplace=True)

In [52]:
test=test.join(encodingdatatest[cols1])

In [53]:
test['TotalCharges'] = test['TotalCharges'].replace(' ', value=0)
test.TotalCharges = pd.to_numeric(test.TotalCharges)

In [54]:
scalardatatest=ss.fit(test[['tenure','MonthlyCharges','TotalCharges']])
datatest=scalardatatest.transform(test[['tenure','MonthlyCharges','TotalCharges']])
datatest=pd.DataFrame(datatest,columns=['tenure','MonthlyCharges','TotalCharges'])
test.drop(columns=['tenure','MonthlyCharges','TotalCharges'],inplace=True)
test=test.join(datatest)

In [55]:
test.sample(n=3)

SeniorCitizen  gender  Partner  Dependents  PhoneService  MultipleLines  \
232              0       1        0           0             0              0   
627              0       1        1           1             1              0   
507              0       0        1           0             1              1   

     InternetService  OnlineSecurity  OnlineBackup  DeviceProtection  \
232                0               0             0                 0   
627                0               0             0                 0   
507                0               1             0                 0   

     TechSupport  StreamingTV  StreamingMovies  Contract  PaperlessBilling  \
232            0            0                0         0                 1   
627            0            0                0         0                 0   
507            0            1                0         0                 1   

     PaymentMethod    tenure  MonthlyCharges  TotalCharges  
232              2 -0.966255       -1.323404     -0.925242  
627              0 -1.006950       -0.667396     -0.846372  
507              0 -0.762780        0.000267     -0.594266

#### Logistic Regression

In [56]:
lr=LogisticRegression()

In [57]:
lr.fit(X_train,y_train)

LogisticRegression()

In [58]:
lr_predictions=lr.predict(X_test)

In [60]:
print(confusion_matrix(y_test,lr_predictions))
print(classification_report(y_test,lr_predictions))
print("Accuracy Score {}".format(accuracy_score(y_test,lr_predictions)))

[[734  80]
 [138 175]]
              precision    recall  f1-score   support

           0       0.84      0.90      0.87       814
           1       0.69      0.56      0.62       313

    accuracy                           0.81      1127
   macro avg       0.76      0.73      0.74      1127
weighted avg       0.80      0.81      0.80      1127

Accuracy Score 0.8065661047027507


#### Decision Tree

In [61]:
dtc=DecisionTreeClassifier()

In [62]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier()

In [63]:
dt_predictions=dtc.predict(X_test)

In [64]:
print(confusion_matrix(y_test,dt_predictions))
print(classification_report(y_test,dt_predictions))
print("Accuracy Score {}".format(accuracy_score(y_test,dt_predictions)))

[[644 170]
 [142 171]]
              precision    recall  f1-score   support

           0       0.82      0.79      0.81       814
           1       0.50      0.55      0.52       313

    accuracy                           0.72      1127
   macro avg       0.66      0.67      0.66      1127
weighted avg       0.73      0.72      0.73      1127

Accuracy Score 0.7231588287488908


#### Random Forest

In [65]:
rfc=RandomForestClassifier()

In [66]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [67]:
rf_predictions=rfc.predict(X_test)

In [68]:
print(confusion_matrix(y_test,rf_predictions))
print(classification_report(y_test,rf_predictions))
print("Accuracy Score {}".format(accuracy_score(y_test,rf_predictions)))

[[743  71]
 [156 157]]
              precision    recall  f1-score   support

           0       0.83      0.91      0.87       814
           1       0.69      0.50      0.58       313

    accuracy                           0.80      1127
   macro avg       0.76      0.71      0.72      1127
weighted avg       0.79      0.80      0.79      1127

Accuracy Score 0.7985803016858918


#### Randomized Search Cv - Random Forest

In [69]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt','log2']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 1000,10)]
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10,14]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4,6,8]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['entropy', 'gini']}


In [70]:
rf_randomcv=RandomizedSearchCV(estimator=rfc,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,
                               random_state=100,n_jobs=-1)
### fit the randomized model
rf_randomcv.fit(X_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [71]:
rf_randomcv.best_params_

{'n_estimators': 400,
 'min_samples_split': 10,
 'min_samples_leaf': 6,
 'max_features': 'auto',
 'max_depth': 670,
 'criterion': 'gini'}

In [72]:
best_random_grid=rf_randomcv.best_estimator_

In [73]:
rf_predictions_rs=best_random_grid.predict(X_test)

In [74]:
print(confusion_matrix(y_test,rf_predictions_rs))
print(classification_report(y_test,rf_predictions_rs))
print("Accuracy Score {}".format(accuracy_score(y_test,rf_predictions_rs)))

[[750  64]
 [153 160]]
              precision    recall  f1-score   support

           0       0.83      0.92      0.87       814
           1       0.71      0.51      0.60       313

    accuracy                           0.81      1127
   macro avg       0.77      0.72      0.73      1127
weighted avg       0.80      0.81      0.80      1127

Accuracy Score 0.8074534161490683


#### Predicting for Test dataset with RandomForest with Randomized Search as I got best Accuracy score for this

In [75]:
predictions=best_random_grid.predict(test)

In [78]:
prediction = pd.DataFrame(predictions, columns=['predictions']).to_csv('prediction.csv',index=False,header=False)

#### Trying with another option, removing, TotalCharges, MonthlyCharges and using OneHot Encoding with Contract and PaymentMethod

In [79]:
df_train=pd.read_csv('Churn_train.csv')
df_train.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  5442-PPTJY    Male              0     Yes        Yes      12          Yes   
1  6261-RCVNS  Female              0      No         No      42          Yes   
2  2176-OSJUV    Male              0     Yes         No      71          Yes   
3  6161-ERDGD    Male              0     Yes        Yes      71          Yes   
4  2364-UFROM    Male              0      No         No      30          Yes   

  MultipleLines InternetService       OnlineSecurity  ...  \
0            No              No  No internet service  ...   
1            No             DSL                  Yes  ...   
2           Yes             DSL                  Yes  ...   
3           Yes             DSL                  Yes  ...   
4            No             DSL                  Yes  ...   

      DeviceProtection          TechSupport          StreamingTV  \
0  No internet service  No internet service  No internet service   
1                  Yes                  Yes                   No   
2                   No                  Yes                   No   
3                  Yes                  Yes                  Yes   
4                   No                  Yes                  Yes   

       StreamingMovies  Contract PaperlessBilling              PaymentMethod  \
0  No internet service  Two year               No               Mailed check   
1                  Yes  One year               No    Credit card (automatic)   
2                   No  Two year               No  Bank transfer (automatic)   
3                  Yes  One year               No           Electronic check   
4                   No  One year               No           Electronic check   

  MonthlyCharges  TotalCharges Churn  
0          19.70        258.35    No  
1          73.90       3160.55   Yes  
2          65.15       4681.75    No  
3          85.45       6300.85    No  
4          70.40       2044.75    No  

[5 rows x 21 columns]

In [80]:
df_train.drop(columns=['customerID','MonthlyCharges','TotalCharges'],inplace=True)

In [81]:
#change the 'No phone/internet service' to 'No', because it's not adding any new informaion
df_train=df_train.replace(to_replace='No internet service',value='No')
df_train=df_train.replace(to_replace='No phone service',value='No')

In [86]:
df_train['PaymentMethod']=df_train['PaymentMethod'].replace(to_replace='Bank transfer (automatic)',value='Bank transfer')
df_train['PaymentMethod']=df_train['PaymentMethod'].replace(to_replace='Credit card (automatic)',value='Credit card')

In [87]:
cols2=['gender','Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup',
     'DeviceProtection','TechSupport','StreamingTV','StreamingMovies','PaperlessBilling','Churn']

In [88]:
data_encode=df_train[cols2].apply(le.fit_transform)

In [89]:
df_train.drop(columns=cols2,inplace=True)

In [90]:
df_train=df_train.join(data_encode[cols2])

In [92]:
df_train.sample(n=3)

SeniorCitizen  tenure        Contract  PaymentMethod  gender  Partner  \
1359              0      13        Two year    Credit card       0        0   
1445              0      31  Month-to-month  Bank transfer       1        1   
1187              0      68        One year    Credit card       1        0   

      Dependents  PhoneService  MultipleLines  InternetService  \
1359           1             1              1                0   
1445           1             0              0                0   
1187           0             1              0                1   

      OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  \
1359               1             1                 1            1   
1445               1             0                 0            1   
1187               0             1                 1            0   

      StreamingTV  StreamingMovies  PaperlessBilling  Churn  
1359            1                1                 0      0  
1445            0                0                 0      1  
1187            0                0                 0      0

In [95]:
df_train=pd.get_dummies(df_train,columns=['Contract','PaymentMethod'],drop_first=True)

In [96]:
df_train.sample(n=3)

SeniorCitizen  tenure  gender  Partner  Dependents  PhoneService  \
949               0      65       1        1           1             1   
3553              0      37       1        0           0             1   
4970              1      43       1        0           0             1   

      MultipleLines  InternetService  OnlineSecurity  OnlineBackup  ...  \
949               1                1               1             0  ...   
3553              1                1               0             0  ...   
4970              1                1               0             0  ...   

      TechSupport  StreamingTV  StreamingMovies  PaperlessBilling  Churn  \
949             1            1                1                 0      1   
3553            1            1                1                 0      1   
4970            0            1                0                 1      0   

      Contract_One year  Contract_Two year  PaymentMethod_Credit card  \
949                   0                  1                          0   
3553                  0                  0                          0   
4970                  0                  0                          0   

      PaymentMethod_Electronic check  PaymentMethod_Mailed check  
949                                0                           0  
3553                               0                           0  
4970                               1                           0  

[3 rows x 21 columns]

In [100]:
X=df_train.drop('Churn',axis=1)
y=df_train['Churn']

In [101]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1)

#### Working with Test Data

In [98]:
df_test=pd.read_csv('Churn_test.csv')
df_test.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  8879-ZKJOF  Female              0      No         No      41          Yes   
1  0201-MIBOL  Female              1      No         No      66          Yes   
2  1600-DILPE  Female              0      No         No      12          Yes   
3  8601-QACRS  Female              0      No         No       5          Yes   
4  7919-ZODZZ  Female              0     Yes        Yes      10          Yes   

  MultipleLines InternetService OnlineSecurity OnlineBackup DeviceProtection  \
0            No             DSL            Yes           No              Yes   
1           Yes     Fiber optic            Yes           No               No   
2            No             DSL             No           No               No   
3           Yes             DSL             No           No               No   
4            No             DSL             No          Yes              Yes   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0         Yes         Yes             Yes        One year              Yes   
1          No         Yes             Yes        Two year              Yes   
2          No          No              No  Month-to-month              Yes   
3          No          No              No  Month-to-month              Yes   
4          No          No             Yes        One year              Yes   

               PaymentMethod  MonthlyCharges TotalCharges  
0  Bank transfer (automatic)           79.85      3320.75  
1  Bank transfer (automatic)          102.40      6471.85  
2  Bank transfer (automatic)           45.00       524.35  
3               Mailed check           50.60       249.95  
4               Mailed check           65.90       660.05

In [99]:
df_test.drop(columns=['customerID','MonthlyCharges','TotalCharges'],inplace=True)

In [102]:
#change the 'No phone/internet service' to 'No', because it's not adding any new informaion
df_test=df_test.replace(to_replace='No internet service',value='No')
df_test=df_test.replace(to_replace='No phone service',value='No')

In [103]:
df_test['PaymentMethod']=df_test['PaymentMethod'].replace(to_replace='Bank transfer (automatic)',value='Bank transfer')
df_test['PaymentMethod']=df_test['PaymentMethod'].replace(to_replace='Credit card (automatic)',value='Credit card')

In [104]:
cols3=['gender','Partner','Dependents','PhoneService','MultipleLines','InternetService','OnlineSecurity','OnlineBackup',
     'DeviceProtection','TechSupport','StreamingTV','StreamingMovies','PaperlessBilling']

In [105]:
data_encode_test=df_test[cols3].apply(le.fit_transform)

In [106]:
df_test.drop(columns=cols3,inplace=True)

In [107]:
df_test=df_test.join(data_encode_test[cols3])

In [124]:
df_test.sample(n=3)

SeniorCitizen  tenure        Contract     PaymentMethod  gender  Partner  \
601              0      40  Month-to-month  Electronic check       1        0   
279              0      29  Month-to-month      Mailed check       1        0   
140              0      31  Month-to-month       Credit card       0        0   

     Dependents  PhoneService  MultipleLines  InternetService  OnlineSecurity  \
601           0             1              0                0               0   
279           1             0              0                0               1   
140           1             1              1                1               0   

     OnlineBackup  DeviceProtection  TechSupport  StreamingTV  \
601             0                 0            1            0   
279             1                 1            1            0   
140             0                 0            0            1   

     StreamingMovies  PaperlessBilling  
601                0                 1  
279                0                 1  
140                0                 1

In [127]:
df_test=pd.get_dummies(df_test,columns=['Contract','PaymentMethod'],drop_first=True)

In [128]:
df_test.sample(n=3)

SeniorCitizen  tenure  gender  Partner  Dependents  PhoneService  \
787               0      13       1        0           0             1   
1329              0      25       0        1           0             1   
187               1      32       1        0           0             1   

      MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
787               0                2               0             0   
1329              0                2               0             0   
187               1                1               0             0   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
787                  0            0            0                0   
1329                 0            0            0                0   
187                  0            0            1                1   

      PaperlessBilling  Contract_One year  Contract_Two year  \
787                  1                  1                  0   
1329                 1                  1                  0   
187                  1                  0                  0   

      PaymentMethod_Credit card  PaymentMethod_Electronic check  \
787                           0                               1   
1329                          0                               0   
187                           1                               0   

      PaymentMethod_Mailed check  
787                            0  
1329                           0  
187                            0

#### Logistic Regression

In [109]:
lr.fit(X_train,y_train)

LogisticRegression()

In [110]:
lr_predictions1=lr.predict(X_test)

In [111]:
print(confusion_matrix(y_test,lr_predictions1))
print(classification_report(y_test,lr_predictions1))
print("Accuracy Score {}".format(accuracy_score(y_test,lr_predictions1)))

[[749  65]
 [163 150]]
              precision    recall  f1-score   support

           0       0.82      0.92      0.87       814
           1       0.70      0.48      0.57       313

    accuracy                           0.80      1127
   macro avg       0.76      0.70      0.72      1127
weighted avg       0.79      0.80      0.78      1127

Accuracy Score 0.7976929902395741


#### Decision Tree

In [112]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier()

In [113]:
dt_predictions=dtc.predict(X_test)

In [114]:
print(confusion_matrix(y_test,dt_predictions))
print(classification_report(y_test,dt_predictions))
print("Accuracy Score {}".format(accuracy_score(y_test,dt_predictions)))

[[664 150]
 [156 157]]
              precision    recall  f1-score   support

           0       0.81      0.82      0.81       814
           1       0.51      0.50      0.51       313

    accuracy                           0.73      1127
   macro avg       0.66      0.66      0.66      1127
weighted avg       0.73      0.73      0.73      1127

Accuracy Score 0.7284826974267968


#### Random Forest

In [115]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [116]:
rf_predictions=rfc.predict(X_test)

In [117]:
print(confusion_matrix(y_test,rf_predictions))
print(classification_report(y_test,rf_predictions))
print("Accuracy Score {}".format(accuracy_score(y_test,rf_predictions)))

[[742  72]
 [163 150]]
              precision    recall  f1-score   support

           0       0.82      0.91      0.86       814
           1       0.68      0.48      0.56       313

    accuracy                           0.79      1127
   macro avg       0.75      0.70      0.71      1127
weighted avg       0.78      0.79      0.78      1127

Accuracy Score 0.7914818101153505


#### Randomized Search Cv - Random Forest

In [118]:
rf_randomcv1=RandomizedSearchCV(estimator=rfc,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,
                               random_state=100,n_jobs=-1)
### fit the randomized model
rf_randomcv1.fit(X_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [119]:
rf_randomcv1.best_params_

{'n_estimators': 1400,
 'min_samples_split': 10,
 'min_samples_leaf': 8,
 'max_features': 'auto',
 'max_depth': 450,
 'criterion': 'gini'}

In [120]:
best_random_grid1=rf_randomcv1.best_estimator_

In [121]:
rf_predictions_rs1=best_random_grid1.predict(X_test)

In [122]:
print(confusion_matrix(y_test,rf_predictions_rs1))
print(classification_report(y_test,rf_predictions_rs1))
print("Accuracy Score {}".format(accuracy_score(y_test,rf_predictions_rs1)))

[[763  51]
 [160 153]]
              precision    recall  f1-score   support

           0       0.83      0.94      0.88       814
           1       0.75      0.49      0.59       313

    accuracy                           0.81      1127
   macro avg       0.79      0.71      0.74      1127
weighted avg       0.81      0.81      0.80      1127

Accuracy Score 0.8127772848269743


#### Predicting for Test dataset with RandomForest with Randomized Search as I got best Accuracy score for this

In [129]:
predictions1=best_random_grid1.predict(df_test)

In [131]:
prediction1 = pd.DataFrame(predictions1, columns=['predictions']).to_csv('prediction1.csv',index=False,header=False)

In [136]:
df=pd.DataFrame(predictions1, columns=['predictions'])

In [139]:
df=df.replace(to_replace=1,value='Yes')
df=df.replace(to_replace=0,value='No')

In [141]:
df = df.to_csv('prediction1.csv')